// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxhhthcjqtypbdflbreh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4aGh0aGNqcXR5cGJkZmxicmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzY4NzAsImV4cCI6MjA3MjY1Mjg3MH0.MBt0TdJPSjs5_IXeR04A4MJWu9N_j1dzZ5wz2k3InmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});